spring:
  application:
    name: flight-manager
  datasource:
    # This URL configures the H2 database to remain open as long as the JVM is running, stay open after JVM shutdown,
    # automatically reconnect on connection loss, and operate in PostgreSQL compatibility mode.
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    # TODO: Enter value
    username:
    # TODO: Enter value
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
  mvc:
    # Required for FrontEndController to forward requests to React
    pathMatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    # TODO: Enter value
    host:
    # TODO: Enter value
    port:
    # TODO: Enter value
    username:
    # TODO: Enter value
    password:
    # TODO: Enter value
    from:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    reservation:
      subject: "Потвърждение за резервация"
      body-template: "Потвърдена резервация за полет от {from} за {to} на {departureTime} за пътници на борй: {passengerCount}."

server:
  port: 8080

jwt:
  # TODO: Enter value (base64-encoded string)
  secret:
  access:
    # 1 hour
    duration-seconds: 3600
  refresh:
    # 7 days
    duration-seconds: 604800

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

accounts:
  admin:
    # TODO: Enter value
    username:
    # TODO: Enter value
    password:
    email: admin@fake.com
    first-name: John
    last-name: Doe
    personal-identification-number: 111111111
    address: 5861 Arctic Blvd, Anchorage, Alaska 99518
    phone-number: 123456789

