spring:
  application:
    name: flight-manager
  datasource:
#    url: jdbc:h2:mem:flight_manager
    # This URL configures the H2 database to remain open as long as the JVM is running, stay open after JVM shutdown,
    # automatically reconnect on connection loss, and operate in PostgreSQL compatibility mode.
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: admin
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # TODO: remove
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      # access h2 console at http://localhost:${server.port}/${server.servlet.context-path}/h2-console/
      # (same port and path as the application, i.e. http://localhost:8080/api/h2-console/ )
      path: /h2-console
      settings:
        # prevent trace output
        trace: false
        # disable remote access
        web-allow-others: false
  # TODO: Remove
  mvc:
    log-request-details: true

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret:
  access:
    # 1 hour
    duration-seconds: 3600
  refresh:
    # 7 days
    duration-seconds: 604800

# TODO: remove
logging:
  level:
    org:
      springframework: DEBUG
